### ISSUE TITLE
Feature request, disable some feature via cvar / config files

### ISSUE THREAD

**Issue by krakerz** [Morris1927/DropinMultiplayer#3]
as title said,
since the item's starter is kinda bugged right now
it would be great if we can turn it off
so the main feature is dropingame only
while sub feature is, item starter and spawnas command (spawnas is easy to abused while playing with other who knows the command, and tend to ruin the game)

**Comment by Morris1927** [comment]
Hi, sorry I didn't notice these comments until now. I couldn't replicate the bug with items being duplicated when you restart, so I've added a check when the character gets created which hopefully fixes it. With the spawn_as command I've added it into the config with a host only option, or disabling it completely, along with being able to turn off starting items.

**Comment by krakerz** [comment]
thanks for the config feature, now i can disable it completely :D
as for the bug itself, with the latest version (just updated today, the game) it seems there is no problem for the bug (even with 2.0.0) i assume it's earlier something incompatible with other mod
but since you already add the check things, probably it won't appear again
