### ISSUE TITLE
spawnas command no longer working

### ISSUE THREAD

**Issue by Jinjo90** [Morris1927/DropinMultiplayer#4]
DropinMultiplayer [v2.0.0]

When submitting 'spawnas' command displays the error code shown below. However, the main function to join an in-game session still works. 

![Capture](https://user-images.githubusercontent.com/49699629/56249463-c5718e00-60a3-11e9-98db-3552aeb19b26.PNG)

**Comment by Morris1927** [comment]
Hi, this has been fixed in the latest update, thank you for the feedback (side note, spawnas is now spawn_as)
